package proyecto_final_ingrid_claudia;

/**
 *
 * @author 1234
 */
public class cartelera3 extends javax.swing.JFrame {

    /**
     * Creates new form cartelera
     */
    public cartelera3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        lblLuz2 = new javax.swing.JLabel();
        lblLuz1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblLuz3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(0, 0, 0));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLuz2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/luz_11.jpg"))); // NOI18N
        lblLuz2.setText("jLabel1");
        panel1.add(lblLuz2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, 120));

        lblLuz1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/luz_3.jpg"))); // NOI18N
        lblLuz1.setText("jLabel1");
        panel1.add(lblLuz1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 110, 120));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Luz De Luna");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 160, 31));

        lblLuz3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/luz_2.jpg"))); // NOI18N
        lblLuz3.setText("jLabel1");
        panel1.add(lblLuz3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 110, 120));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Una producción de: Jay Daniel y Glenn Gordon");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 300, 50));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Narra la vida de un joven desde la infacia hasta la edad adulta, ");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 390, 50));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("mientras lucha por encontrar su lugar en el mundo mientras");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 390, 40));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("crece en barrio áspero en Miami.");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 390, 50));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 300));

        jLabel2.setText("El payaso regresa..");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 220));
        jLabel2.getAccessibleContext().setAccessibleName("El payaso regresa..\nPreparate para \nrevivir tus miedos\nde la infancia\n\n¿Estas listo para\nflotar?\n\nuna produccion de\nRoy Lee");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    /* public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cartelera().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel lblLuz1;
    public javax.swing.JLabel lblLuz2;
    public javax.swing.JLabel lblLuz3;
    public javax.swing.JPanel panel1;
    // End of variables declaration//GEN-END:variables
}
