
package proyecto_final_ingrid_claudia;

/**
 *
 * @author 1234
 */
public class cartelera extends javax.swing.JFrame {

    /**
     * Creates new form cartelera
     */
    public cartelera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        lblPelicula1 = new javax.swing.JLabel();
        lblPelicula2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(0, 0, 0));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPelicula1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/it_1.png"))); // NOI18N
        lblPelicula1.setText("jLabel1");
        panel1.add(lblPelicula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 38, 128, 210));

        lblPelicula2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/it_2.png"))); // NOI18N
        lblPelicula2.setText("jLabel1");
        panel1.add(lblPelicula2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 119, -1));

        jLabel1.setFont(new java.awt.Font("Chiller", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("It");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 0, 60, 31));

        jLabel3.setFont(new java.awt.Font("Chiller", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("volar?");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 200, 120, 26));

        jLabel4.setFont(new java.awt.Font("Chiller", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Una produccion\n");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 50, 110, 26));

        jLabel5.setFont(new java.awt.Font("Chiller", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("de Roy Lee");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 99, 26));

        jLabel6.setFont(new java.awt.Font("Chiller", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Preparate para ");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 110, 26));

        jLabel7.setFont(new java.awt.Font("Chiller", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Revivir tus miedos");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 140, 26));

        jLabel8.setFont(new java.awt.Font("Chiller", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("de la infancia");
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 99, 26));

        jLabel9.setFont(new java.awt.Font("Chiller", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("¿Estas listo para");
        panel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 180, 120, 26));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 300));

        jLabel2.setText("El payaso regresa..");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 220));
        jLabel2.getAccessibleContext().setAccessibleName("El payaso regresa..\nPreparate para \nrevivir tus miedos\nde la infancia\n\n¿Estas listo para\nflotar?\n\nuna produccion de\nRoy Lee");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cartelera().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel lblPelicula1;
    public javax.swing.JLabel lblPelicula2;
    public javax.swing.JPanel panel1;
    // End of variables declaration//GEN-END:variables
}
