package proyecto_final_ingrid_claudia;

/**
 *
 * @author Claudia Cortes
 */
public class Imprimir_Ticket extends javax.swing.JPanel {

    /**
     * Creates new form Imprimir_Ticket
     */
    public Imprimir_Ticket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        peli1 = new javax.swing.JLabel();
        btnLUZ = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnIT = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnA = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("AR BONNIE", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cartelera");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 210, 47));

        peli1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/it_11.jpg"))); // NOI18N
        peli1.setText("jLabel2");
        add(peli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 180, 270));

        btnLUZ.setBackground(new java.awt.Color(0, 0, 0));
        btnLUZ.setFont(new java.awt.Font("AR BONNIE", 1, 14)); // NOI18N
        btnLUZ.setForeground(new java.awt.Color(0, 102, 102));
        btnLUZ.setText("Detalles");
        btnLUZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLUZActionPerformed(evt);
            }
        });
        add(btnLUZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ana_1.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 190, 290));

        btnIT.setBackground(new java.awt.Color(0, 0, 0));
        btnIT.setFont(new java.awt.Font("AR BONNIE", 1, 14)); // NOI18N
        btnIT.setForeground(new java.awt.Color(51, 51, 51));
        btnIT.setText("Detalles");
        btnIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnITActionPerformed(evt);
            }
        });
        add(btnIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/luz_1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 180, 270));

        btnA.setBackground(new java.awt.Color(0, 0, 0));
        btnA.setFont(new java.awt.Font("AR BONNIE", 1, 14)); // NOI18N
        btnA.setForeground(new java.awt.Color(102, 0, 0));
        btnA.setText("Detalles");
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });
        add(btnA, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        jLabel4.setText("jLabel4");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 540, 360));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLUZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLUZActionPerformed
        detalles3 CambiarImg = new detalles3();
        CambiarImg.CambioImagen3();
    }//GEN-LAST:event_btnLUZActionPerformed

    private void btnITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnITActionPerformed
        detalles CambiarImg = new detalles();
        CambiarImg.CambioImagen();
    }//GEN-LAST:event_btnITActionPerformed

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        detalles2 CambiarImg = new detalles2();
        CambiarImg.CambioImagen2();
    }//GEN-LAST:event_btnAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnIT;
    private javax.swing.JButton btnLUZ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel peli1;
    // End of variables declaration//GEN-END:variables
}
